title: "Wavy Resume, A Demo online resume/portfolio"
author:
  first_name: "Wavy"
  last_name: "Resume"
  summary: "This is a summary of why you should visit this webpage for SEO purposes"
  gender: 'n/a'
description: "A demo portfolio website."
siteUrl: ""
logo: ""
icons: []
